name: Pipeline
on: [push]

jobs:
    pycicd:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                python-version: 3.8

            - name: Install tests dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: pycicd-supreme-fortnight
              uses: pritul95/pycicd-supreme-fortnight@V0.1
              with:
                run_type: pytest
                args: .
              env:
                LOG_LEVEL: DEBUG
